/*
                                   )
                                  (.)
                                  .|.
                                  | |
                              _.--| |--._
                           .-';  ;`-'& ; `&.
                          \   &  ;    &   &_/
                           |"""---...---"""|
                           \ | | | | | | | /
                            `---.|.|.|.---'

 * This file is generated by bake.lang.c for your convenience. Headers of
 * dependencies will automatically show up in this file. Include bake_config.h
 * in your main project file. Do not edit! */

#ifndef TOWER_DEFENSE_BAKE_CONFIG_H
#define TOWER_DEFENSE_BAKE_CONFIG_H

/* Headers of public dependencies */
#include <flecs.h>
#include <flecs_components_transform.h>
#include <flecs_components_graphics.h>
#include <flecs_components_geometry.h>
#include <flecs_components_physics.h>
#include <flecs_components_gui.h>
#include <flecs_components_input.h>
#include <flecs_systems_transform.h>
#include <flecs_systems_physics.h>
#include <flecs_systems_sokol.h>
#include <flecs_game.h>

#endif

